- id: sbt-fatal-warnings
  name: Scala fatal warnings
  stages: [pre-commit,pre-push]
  language: python
  entry: sbt-fatal-warnings
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '0.19.0'
- id: sbt-unused-imports
  name: Scala unused imports (+ fatal warnings)
  stages: [pre-commit,pre-push]
  language: python
  entry: sbt-fatal-warnings --add_arg='-Ywarn-unused-import'
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '0.19.0'
- id: scalafmt-check
  name: scalafmt check formatting
  description: Validate code formatting with scalafmt
  entry: scalafmt --test
  args: [--mode=changed]
  language: system
  stages: [pre-commit,pre-push]
  always_run: true
  pass_filenames: false
  minimum_pre_commit_version: '2.8.0'
- id: scalafmt-autofix
  name: scalafmt format code
  description: Automatically fix code formatting with scalafmt
  entry: ./shell/scalafmt-autofix.sh
  args: [--mode=changed]
  language: script
  stages: [pre-commit]
  always_run: true
  pass_filenames: false
  require_serial: true
  minimum_pre_commit_version: '2.8.0'
